services:
  - type: web
    name: lenscamdio-website
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 